const ThemeVariables = [
  'background',
  'foreground',
  'card',
  'card-foreground',
  'popover',
  'popover-foreground',
  'primary',
  'primary-foreground',
  'secondary',
  'secondary-foreground',
  'muted',
  'muted-foreground',
  'accent',
  'accent-foreground',
  'destructive',
  'destructive-foreground',
  'border',
  'input',
  'ring',
] as const;

const defaultValues = {
  ['background']: '',
  ['foreground']: '',
  ['card']: '',
  ['card-foreground']: '',
  ['popover']: '',
  ['popover-foreground']: '',
  ['primary']: '',
  ['primary-foreground']: '',
  ['secondary']: '',
  ['secondary-foreground']: '',
  ['muted']: '',
  ['muted-foreground']: '',
  ['accent']: '',
  ['accent-foreground']: '',
  ['destructive']: '',
  ['destructive-foreground']: '',
  ['border']: '',
  ['input']: '',
  ['ring']: '',
};

export { ThemeVariables, defaultValues };
